version: 38
jobs:
- name: Generate NPM Package
  jobExecutor: Local-Pi5
  steps:
  - !CheckoutStep
    name: Get Repo
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: NodeJS Builder
    runInContainer: true
    image: node:20
    interpreter: !ShellInterpreter
      shell: bash
      commands: |
        apt-get update
        apt-get install -y zip

        npm install
        npm install cors
        npm install express
        npm run build
        ls
        rm -rf .git
        zip -r latest.zip .
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishSiteStep
    name: Publish ZIP
    artifacts: latest.zip
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Send Webhook
    runInContainer: true
    image: node:20
    interpreter: !ShellInterpreter
      shell: bash
      commands: |
        curl -X POST http://@secret:IP PI4@:4000/deploy
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
