version: 40
jobs:
- name: Generate NPM Package
  jobExecutor: Local-Pi5
  steps:
  - !CheckoutStep
    name: Get Repo
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: NodeJS Builder
    runInContainer: true
    image: node:20
    interpreter: !ShellInterpreter
      shell: bash
      commands: "wget http://ftp.de.debian.org/debian/pool/main/z/zip/zip_3.0-13_arm64.deb\n\ndpkg -i zip_3.0-13_arm64.deb \n\nnpm install\nnpm install cors\nnpm install express\nnpm run build\nls\nrm -rf .git\nzip -r latest.zip .\n"
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - !PublishSiteStep
    name: Publish ZIP
    artifacts: latest.zip
    condition: SUCCESSFUL
    optional: false
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: Push to Github
  steps:
  - !CheckoutStep
    name: Get Code
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: SUCCESSFUL
    optional: false
  - !PushRepository
    name: Push to Github
    remoteUrl: https://github.com/Limo123123/nodejs.git
    userName: Limo123123
    passwordSecret: gh
    force: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !BranchUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
